services:
  postgres:
    container_name: dotnetcleantemplate.postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-DotNetCleanTemplate}
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5434}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dotnetcleantemplate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: dotnetcleantemplate.redis
    image: redis:7-alpine
    ports:
      - "${REDIS_EXTERNAL_PORT:-6380}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    networks:
      - dotnetcleantemplate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dotnetcleantemplate.api:
    container_name: dotnetcleantemplate.api
    image: ${DOCKER_REGISTRY-}dotnetcleantemplateapi
    build:
      context: .
      dockerfile: DotNetCleanTemplate.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-DotNetCleanTemplate}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING:-redis:6379,abortConnect=false}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JWT_KEY=${JWT_KEY:-mysupersecretkey1234567890123456}
      - JWT_ISSUER=${JWT_ISSUER:-localhost}
      - JWT_AUDIENCE=${JWT_AUDIENCE:-localhost}
      - INIT_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD:-Admin123!}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dotnetcleantemplate-network

volumes:
  postgres_data:
  redis_data:

networks:
  dotnetcleantemplate-network:
    driver: bridge
    
