global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # .NET Application
  - job_name: 'dotnetcleantemplate-api'
    static_configs:
      - targets: ['dotnetcleantemplate.api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL (if you want to monitor it)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    # Note: You'll need to install postgres_exporter for this to work

  # Redis (if you want to monitor it)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    # Note: You'll need to install redis_exporter for this to work 