name: Build and Publish Template Package

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
          echo "Extracted version: $TAG"
          echo "version=$TAG" >> $GITHUB_ENV
          
      - name: Update package version
        run: |
          # Update PackageVersion in templatepack.csproj
          sed -i "s/<PackageVersion>.*<\/PackageVersion>/<PackageVersion>${{ env.version }}<\/PackageVersion>/g" .template.config/templatepack.csproj
          echo "Updated PackageVersion to ${{ env.version }}"
        env:
          VERSION: ${{ env.version }}
          
      - name: Show updated version
        run: |
          echo "Current PackageVersion in templatepack.csproj:"
          grep "<PackageVersion>" .template.config/templatepack.csproj
          
      - name: Restore dependencies
        run: dotnet restore .template.config/templatepack.csproj

      - name: Build
        run: dotnet build .template.config/templatepack.csproj --configuration Release --no-restore

      - name: Build and Pack
        run: dotnet pack .template.config/templatepack.csproj --configuration Release --output ./nupkgs /p:PackageVersion=${{ env.version }}
        env:
          VERSION: ${{ env.version }}

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source nuget.org 