name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore source/DotNetCleanTemplate.sln

      - name: Build
        run: dotnet build source/DotNetCleanTemplate.sln --no-restore

      - name: Test
        run: dotnet test source/DotNetCleanTemplate.sln --no-build --logger "console;verbosity=detailed"